const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),results=[];
const fake={innerHTML:'',textContent:'',classList:{toggle(){},add(){},remove(){}},addEventListener(){},open:false};
const ctx=vm.createContext({window:{addEventListener(){},scrollTo(){}},document:{querySelector(){return fake},querySelectorAll(){return[]},addEventListener(){}},console,setInterval(){},setTimeout(){},clearTimeout(){},localStorage:{setItem(){}},fetch(){throw Error('Unexpected test fetch')},Blob,URL});
vm.runInContext(fs.readFileSync(path.join(root,'dist/data.js'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(root,'dist/app.js'),'utf8').replace(/init\(\);\s*$/,''),ctx);
const run=s=>vm.runInContext(s,ctx);
run('state=fresh();persist=()=>{};renderQuiz=()=>{};renderMatch=()=>{};notify=()=>{};');
function check(name,fn){fn();results.push({name,passed:true});console.log('PASS',name)}
check('30 days: 100 words and 50 distinct pairs, covering all new entries',()=>{assert.equal(run('totalDays'),30);assert.equal(run(`Array.from({length:totalDays},(_,n)=>['words','pairs'].every(b=>items(b,n).length===(b==='words'?100:50)&&new Set(items(b,n).map(x=>x.id)).size===items(b,n).length)).every(Boolean)`),true);assert.equal(run(`new Set(Array.from({length:totalDays},(_,n)=>items('words',n)).flat().map(x=>x.id)).size`),run('DATA.words.length'));assert.equal(run(`new Set(Array.from({length:totalDays},(_,n)=>items('pairs',n)).flat().map(x=>x.id)).size`),run('DATA.pairs.length'));});
check('Meaning priority includes precise explanations and rare meanings',()=>{assert.equal(run("DATA.words.find(x=>x.word==='unidimensional').meaning.includes('肤浅')"),true);assert.equal(run("DATA.words.find(x=>x.word==='compromise').meaning.includes('危害')"),true);assert.equal(run("DATA.words.find(x=>x.word==='compromise').base.includes('妥协')"),true)});
check('Daily pass requires learning, quizzes and both matching tracks',()=>{assert.equal(run('completed()'),false);run(`['words','pairs'].forEach(b=>items(b).forEach(x=>day()[b].learned[x.id]=true))`);assert.equal(run('completed()'),false);run(`['words','pairs'].forEach(b=>items(b).forEach(x=>{day()[b].quiz[x.id]=true;day()[b][b==='words'?'match':'pair'][x.id]=true}))`);assert.equal(run('completed()'),true);run(`delete day().words.match[items('words')[99].id]`);assert.equal(run('completed()'),false);run('state=fresh()');});
check('Choice generation has unique options and exactly one/two targets',()=>{run(`for(const book of ['words','pairs'])for(const x of DATA[book].filter((_,i)=>i%53===0)){session={book,mode:'quiz',list:[x],queue:[{id:x.id,dir:0}],selected:[]};question();if(session.question.options.length!==(book==='words'?4:6)||new Set(session.question.options).size!==session.question.options.length||session.question.answers.length!==(book==='words'?1:2)||session.question.answers.some(i=>i<0))throw Error('Invalid question '+x.id);}`)});
check('Wrong answer retries without credit; correct answer credits only once',()=>{run(`state=fresh();session={book:'words',mode:'quiz',group:0,list:[DATA.words[0]],queue:[{id:DATA.words[0].id,dir:0}],selected:[],review:false};question();session.selected=[session.question.answers[0]===0?1:0];submitQuiz();`);assert.equal(run('count("words","quiz")'),0);assert.equal(run('session.queue.length'),1);assert.equal(run('state.mistakes.words[DATA.words[0].id].errors'),1);run(`session.question=null;question();session.selected=session.question.answers.slice();submitQuiz();`);assert.equal(run('count("words","quiz")'),1);assert.equal(run('session.queue.length'),0);});
check('Both directions required for each equivalent pair',()=>{run(`state=fresh();session={book:'pairs',mode:'pair',group:0,list:[DATA.pairs[0]],queue:[{id:DATA.pairs[0].id,dir:0},{id:DATA.pairs[0].id,dir:1}],review:false};question();session.selected=session.question.answers.slice();submitQuiz()`);assert.equal(run('count("pairs","pair")'),0);assert.equal(run('session.queue.length'),1);run(`session.question=null;question();session.selected=session.question.answers.slice();submitQuiz()`);assert.equal(run('count("pairs","pair")'),1);});
check('Matching wrong pair does not grant progress; correct pair does',()=>{run(`state=fresh();session={book:'words',list:items('words'),group:0};prepareMatch();pickMatch('left',DATA.words[0].id);pickMatch('right',DATA.words[1].id);`);assert.equal(run('count("words","match")'),0);run(`pickMatch('left',DATA.words[0].id);pickMatch('right',DATA.words[0].id)`);assert.equal(run('count("words","match")'),1);});
check('Mistakes require two consecutive successes; invalid archives rejected',()=>{run(`const testWord=DATA.words[2];mistake('words',testWord,'quiz');reviewCorrect('words',testWord);`);assert.equal(run('!!state.mistakes.words[DATA.words[2].id]'),true);run(`reviewCorrect('words',DATA.words[2])`);assert.equal(run('!!state.mistakes.words[DATA.words[2].id]'),false);assert.equal(run('!!validArchive({version:1,activeDay:0,days:[]})'),false);assert.equal(run('!!validArchive(state)'),true)});
async function main(){
 const store=path.join(root,'tools/qa-store');fs.mkdirSync(store,{recursive:true});const port=18766,url=`http://127.0.0.1:${port}`;let child;
 async function launch(){child=spawn(process.execPath,[path.join(root,'server.cjs')],{env:{...process.env,GRE_PORT:String(port),GRE_SAVE_DIR:store},windowsHide:true,stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',code=>{if(code)reject(Error('Server exit '+code))})});}
 try{
 await launch();let prev=(await (await fetch(url+'/api/state')).json()).state;let rev=prev?.revision||0;
 const s=JSON.parse(run('JSON.stringify(state)'));s.updated=Date.now();s.resume={mode:'learn',book:'words',group:0,day:0};s.days[0].words.cursor[0]='w2';
 const put=(state,r)=>fetch(url+'/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state,revision:r})});
 let res=await put(s,rev);assert.equal(res.status,200);rev=(await res.json()).revision;
 res=await put({...s,activeDay:1},rev-1);assert.equal(res.status,409);
 res=await put({version:0},rev);assert.equal(res.status,400);
 let restored=(await (await fetch(url+'/api/state')).json()).state;assert.equal(restored.activeDay,0);assert.equal(restored.days[0].words.cursor[0],'w2');assert.equal(restored.days[0].words.match.w1,true);
 child.kill();await new Promise(resolve=>child.once('exit',resolve));await launch();restored=(await (await fetch(url+'/api/state')).json()).state;assert.equal(restored.days[0].words.match.w1,true);assert.equal(restored.days[0].words.cursor[0],'w2');
 res=await put({...s,updated:Date.now()},rev);assert.equal(res.status,200);assert.equal(fs.existsSync(path.join(store,'上一次进度.json')),true);
 for(const route of ['/','/style.css','/app.js','/data.js','/book/full','/book/precise','/book/rare','/book/pairs','/book/zhen'])assert.equal((await fetch(url+route)).status,200,route);
 results.push({name:'File persistence, restart, conflict rejection, invalid state, backups and all book routes',passed:true});console.log('PASS API persistence/restart/concurrency/backups/books');
 }finally{child?.kill();fs.writeFileSync(path.join(root,'tools/验证结果.json'),JSON.stringify({date:'2026-10-06',results},null,2));}
}
main().catch(e=>{console.error(e);process.exitCode=1});
